# Generated by Django 4.2.1 on 2023-06-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yolo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="labels",
            field=models.TextField(blank=True, null=True),
        ),
    ]
