# Generated by Django 4.2.1 on 2023-06-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yolo", "0004_label_remove_post_labels_post_labels"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="labels",
        ),
        migrations.DeleteModel(
            name="Label",
        ),
        migrations.AddField(
            model_name="post",
            name="labels",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
