# Generated by Django 4.2.1 on 2023-06-07 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yolo", "0006_label_remove_post_labels_post_labels"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="labels",
        ),
        migrations.DeleteModel(
            name="Label",
        ),
        migrations.AddField(
            model_name="post",
            name="labels",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
