# Generated by Django 4.2.1 on 2023-06-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="coordinates",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
